# Generated by Django 5.2.4 on 2025-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de la cita"
                    ),
                ),
                (
                    "hour",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de la cita"
                    ),
                ),
                (
                    "ailments",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Padecimientos",
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Diagnóstico",
                    ),
                ),
                (
                    "surgeries",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Cirugías"
                    ),
                ),
                (
                    "reflexology_diagnostics",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Diagnósticos de reflexología",
                    ),
                ),
                (
                    "medications",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Medicamentos",
                    ),
                ),
                (
                    "observation",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "initial_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicial"
                    ),
                ),
                (
                    "final_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha final"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tipo de cita",
                    ),
                ),
                (
                    "room",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Habitación/Consultorio"
                    ),
                ),
                (
                    "social_benefit",
                    models.BooleanField(default=True, verbose_name="Beneficio social"),
                ),
                (
                    "payment_detail",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Detalle de pago",
                    ),
                ),
                (
                    "payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Pago",
                    ),
                ),
                (
                    "ticket_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de ticket"
                    ),
                ),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("COMPLETADO", "Completado"),
                            ("PENDIENTE", "Pendiente"),
                            ("ACTIVO", "Activo"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la cita",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "db_table": "appointments",
                "ordering": ["-appointment_date", "-hour"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre del estado"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de Cita",
                "verbose_name_plural": "Estados de Citas",
                "db_table": "appointment_statuses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de ticket"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Método de pago"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado del ticket",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "tickets",
                "ordering": ["-payment_date"],
            },
        ),
    ]
