# Generated by Django 5.2.4 on 2025-08-27 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments_status", "0001_initial"),
        ("histories_configurations", "0001_initial"),
        ("patients_diagnoses", "0002_initial"),
        ("therapists", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nombre del estado"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Estado de Cita",
                "verbose_name_plural": "Estados de Citas",
                "db_table": "appointment_statuses",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="appointment_name_b2e8b6_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="Fecha de la cita")),
                ("appointment_hour", models.TimeField(verbose_name="Hora de la cita")),
                (
                    "ailments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Padecimientos"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="Diagnóstico"),
                ),
                (
                    "surgeries",
                    models.TextField(blank=True, null=True, verbose_name="Cirugías"),
                ),
                (
                    "reflexology_diagnostics",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Diagnósticos de reflexología",
                    ),
                ),
                (
                    "medications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Medicamentos"
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "initial_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicial"
                    ),
                ),
                (
                    "final_date",
                    models.DateField(blank=True, null=True, verbose_name="Fecha final"),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de cita",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Habitación/Consultorio",
                    ),
                ),
                (
                    "social_benefit",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Beneficio social",
                    ),
                ),
                (
                    "payment_detail",
                    models.TextField(
                        blank=True, null=True, verbose_name="Detalle de pago"
                    ),
                ),
                (
                    "payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Pago",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de ticket",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients_diagnoses.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="histories_configurations.paymenttype",
                        verbose_name="Tipo de pago",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="therapists.therapist",
                        verbose_name="Terapeuta",
                    ),
                ),
                (
                    "appointment_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments_status.appointmentstatus",
                        verbose_name="Estado de la cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita",
                "verbose_name_plural": "Citas",
                "db_table": "appointments",
                "ordering": ["-appointment_date", "-appointment_hour"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de ticket"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(max_length=50, verbose_name="Método de pago"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("paid", "Pagado"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Reembolsado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado del ticket",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments_status.appointment",
                        verbose_name="Cita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "tickets",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "appointment_hour"],
                name="appointment_appoint_68d4d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_status"], name="appointment_appoint_b25c11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["ticket_number"], name="tickets_ticket__4c9624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["payment_date"], name="tickets_payment_5ac8c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status"], name="tickets_status_fbbf05_idx"),
        ),
    ]
