# Generated by Django 5.2.4 on 2025-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_status", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="ticket_number",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
