# Generated by Django 5.2.4 on 2025-08-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("histories_configurations", "0001_initial"),
        ("patients_diagnoses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patients_diagnoses.patient",
                verbose_name="Paciente",
            ),
        ),
    ]
