# Generated by Django 5.2.4 on 2025-08-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentstatus",
            options={
                "managed": False,
                "verbose_name": "Estado de pago",
                "verbose_name_plural": "Estados de pago",
            },
        ),
    ]
