# Generated by Django 5.2.4 on 2025-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "managed": False,
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
