# Generated by Django 5.2.4 on 2025-08-29 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    )
                ],
                verbose_name="Foto de perfil",
            ),
        ),
    ]
