# Generated by Django 5.2.4 on 2025-08-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_profiles", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userverificationcode",
            options={
                "managed": False,
                "ordering": ["-created_at"],
                "verbose_name": "Código de verificación de usuario",
                "verbose_name_plural": "Códigos de verificación de usuarios",
            },
        ),
    ]
