# Generated by Django 5.2.4 on 2025-08-26 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ubigeo_code",
                    models.CharField(db_index=True, max_length=2, unique=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ubigeo_code",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provinces",
                        to="ubi_geo.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ubigeo_code",
                    models.CharField(db_index=True, max_length=5, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="districts",
                        to="ubi_geo.province",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["province", "name"],
                        name="ubi_geo_dis_provinc_f0c5e1_idx",
                    )
                ],
                "unique_together": {("province", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="province",
            index=models.Index(
                fields=["region", "name"], name="ubi_geo_pro_region__ad89cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="province",
            unique_together={("region", "name")},
        ),
    ]
