"""
URL configuration for settings project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/http/urls/

Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # Importa settings
from django.conf.urls.static import static  # Importa static
from django.http import JsonResponse

def health_check(request):
    """Endpoint de health check para Docker"""
    return JsonResponse({'status': 'healthy', 'service': 'reflexo-backend'})

urlpatterns = [
    path('admin/', admin.site.urls),
    path('health/', health_check, name='health_check'),
    
    # 🔌 API Endpoints - Estándar unificado
    path('api/', include([
        # 🏗️ Módulo 1: Arquitectura y Usuarios Base
        path('architect/', include('architect.urls')),
        
        # 👤 Módulo 2: Perfiles de Usuarios
        path('profiles/', include('users_profiles.urls')),
        
        # 🩺 Módulo 3: Pacientes y Diagnósticos
        path('patients/', include('patients_diagnoses.urls')),
        
        # 👨‍⚕️ Módulo 4: Terapeutas (incluye ubicaciones)
        path('therapists/', include('therapists.urls')),
        
        # 📅 Módulo 5: Citas y Estados
        path('appointments/', include('appointments_status.urls')),
        
        # ⚙️ Módulo 6: Historiales y Configuraciones
        path('configurations/', include('histories_configurations.urls')),
        
        # Modulo 7: Ubicaciones Geograficas
        path('locations/', include('ubi_geo.urls')),

        # 📊 Módulo 8: Reportes de Empresas
        path('company/', include('company_reports.urls')),

    ])),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
