# Generated by Django 5.2.4 on 2025-08-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("histories_configurations", "0001_initial"),
        ("ubi_geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de documento"
                    ),
                ),
                (
                    "last_name_paternal",
                    models.CharField(max_length=150, verbose_name="Apellido paterno"),
                ),
                (
                    "last_name_maternal",
                    models.CharField(max_length=150, verbose_name="Apellido materno"),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "birth_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Sexo"
                    ),
                ),
                (
                    "personal_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Referencia personal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                ("email", models.CharField(max_length=254, verbose_name="Email")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "profile_picture",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de eliminación"
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubi_geo.district",
                        verbose_name="Distrito",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="histories_configurations.documenttype",
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubi_geo.province",
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ubi_geo.region",
                        verbose_name="Región",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terapeuta",
                "verbose_name_plural": "Terapeutas",
                "db_table": "therapists",
                "ordering": ["first_name", "last_name_paternal"],
            },
        ),
    ]
