# Generated by Django 5.2.4 on 2025-08-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("therapists", "0001_initial"),
        ("ubi_geo", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carné de Extranjería"),
                            ("PTP", "PTP"),
                            ("CR", "Carné de Refugiado"),
                            ("PAS", "Pasaporte"),
                        ],
                        max_length=10,
                    ),
                ),
                ("document_number", models.CharField(max_length=20, unique=True)),
                ("last_name_paternal", models.CharField(max_length=100)),
                (
                    "last_name_maternal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                (
                    "personal_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Activo"), (False, "Inactivo")], default=True
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "district_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ubi_geo.district",
                    ),
                ),
                (
                    "province_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ubi_geo.province",
                    ),
                ),
                (
                    "region_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ubi_geo.region",
                    ),
                ),
            ],
        ),
    ]
