# Generated by Django 5.2.4 on 2025-08-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histories_configurations", "0001_initial"),
        ("therapists", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="therapist",
            options={"verbose_name": "Terapeuta", "verbose_name_plural": "Terapeutas"},
        ),
        migrations.AlterField(
            model_name="therapist",
            name="document_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="histories_configurations.documenttype",
                verbose_name="Tipo de documento",
            ),
        ),
    ]
