# Generated by Django 5.2.4 on 2025-08-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("architect", "0002_delete_userverificationcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
