# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubi_geo', '0001_initial'),
        ('histories_configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
                'db_table': 'diagnoses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('paternal_lastname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido paterno', db_column='last_name_paternal')),
                ('maternal_lastname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido materno', db_column='last_name_maternal')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('personal_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia personal')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexo', db_column='gender')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono 2')),
                ('email', models.CharField(max_length=254, verbose_name='Email')),
                ('ocupation', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('health_condition', models.TextField(verbose_name='Condición de salud')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories_configurations.documenttype', verbose_name='Tipo de documento')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubi_geo.district', verbose_name='Distrito')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubi_geo.province', verbose_name='Provincia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubi_geo.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(verbose_name='Fecha de diagnóstico')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Síntomas')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Tratamiento')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('diagnose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_diagnoses.diagnosis', verbose_name='Diagnóstico')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_diagnoses.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
                'db_table': 'medical_records',
                'ordering': ['-diagnosis_date', '-created_at'],
                'unique_together': {('patient', 'diagnose')},
            },
        ),
    ]
