# Generated by Django 5.2.4 on 2025-08-26 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("histories_configurations", "0001_initial"),
        ("patients_diagnoses", "0001_initial"),
        ("ubi_geo", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Diagnóstico",
                "verbose_name_plural": "Diagnósticos",
                "db_table": "diagnoses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_number", models.CharField(max_length=20, unique=True)),
                ("paternal_lastname", models.CharField(max_length=100)),
                ("maternal_lastname", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "personal_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=10,
                    ),
                ),
                ("primary_phone", models.CharField(max_length=15)),
                (
                    "secondary_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("ocupation", models.CharField(blank=True, max_length=100, null=True)),
                ("health_condition", models.TextField(blank=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_patients",
                        to="ubi_geo.district",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_patients",
                        to="histories_configurations.documenttype",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_patients",
                        to="ubi_geo.province",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_patients",
                        to="ubi_geo.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis_date", models.DateField()),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("resolved", "Resuelto"),
                            ("chronic", "Crónico"),
                            ("monitoring", "En Monitoreo"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients_diagnoses.diagnosis",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="patients_diagnoses.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Médico",
                "verbose_name_plural": "Historiales Médicos",
                "db_table": "medical_records",
                "ordering": ["-diagnosis_date", "-created_at"],
                "unique_together": {("patient", "diagnosis", "diagnosis_date")},
            },
        ),
    ]
