# Generated by Django 5.2.4 on 2025-08-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_diagnoses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="maternal_lastname",
            field=models.CharField(
                blank=True,
                db_column="last_name_maternal",
                max_length=150,
                null=True,
                verbose_name="Apellido materno",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="paternal_lastname",
            field=models.CharField(
                blank=True,
                db_column="last_name_paternal",
                max_length=150,
                null=True,
                verbose_name="Apellido paterno",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                db_column="gender",
                max_length=50,
                null=True,
                verbose_name="Sexo",
            ),
        ),
    ]
