# Generated by Django 5.2.4 on 2025-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Company Data",
                "verbose_name_plural": "Companies Data",
                "ordering": ["company_name"],
            },
        ),
    ]
