# Generated by Django 5.2.4 on 2025-08-30 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydata",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
                verbose_name="Logo de la empresa",
            ),
        ),
    ]
